# Generated by Django 4.2.5 on 2023-09-11 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEnv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tree_node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stree.service')),
            ],
        ),
        migrations.CreateModel(
            name='TreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024)),
                ('name', models.CharField(max_length=255)),
                ('typ', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreeRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TreeUserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stree.treerole')),
                ('tree_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stree.treenode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEnvHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hosts.host')),
                ('service_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stree.serviceenv')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('git', models.CharField(max_length=255)),
                ('opadmin', models.CharField(max_length=255)),
                ('rdadmin', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('command', models.CharField(max_length=255)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stree.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='tree_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stree.treenode'),
        ),
    ]
