# Generated by Django 4.2.5 on 2023-09-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treerole',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
