# Generated by Django 4.2.5 on 2023-09-15 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0002_treerole_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceenv',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='stree.service'),
        ),
        migrations.AlterField(
            model_name='serviceenv',
            name='tree_node',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stree.treenode'),
        ),
    ]
