# Generated by Django 4.2.5 on 2023-09-15 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0003_serviceenv_service_alter_serviceenv_tree_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceenv',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stree.service'),
        ),
    ]
