# Generated by Django 4.2.5 on 2023-09-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0004_alter_serviceenv_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceconf',
            name='command',
        ),
        migrations.AddField(
            model_name='serviceconf',
            name='build_command',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='serviceconf',
            name='start_command',
            field=models.TextField(null=True),
        ),
    ]
