# Generated by Django 4.2.5 on 2023-09-16 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0005_remove_serviceconf_command_serviceconf_build_command_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('pub_log', models.TextField()),
                ('pub_cmd', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('status', models.CharField(max_length=128)),
                ('operator', models.CharField(max_length=128)),
                ('service_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stree.serviceenv')),
            ],
        ),
        migrations.CreateModel(
            name='BuildHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=128)),
                ('build_cmd', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('status', models.CharField(max_length=128)),
                ('operator', models.CharField(max_length=128)),
                ('service_env', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stree.serviceenv')),
            ],
        ),
    ]
