# Generated by Django 4.2.5 on 2023-09-16 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0006_pubhistory_buildhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildhistory',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='pubhistory',
            name='stop_time',
            field=models.DateTimeField(null=True),
        ),
    ]
