# Generated by Django 4.2.5 on 2023-09-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stree', '0007_alter_buildhistory_stop_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildhistory',
            name='build_log',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='pubhistory',
            name='pub_log',
            field=models.TextField(null=True),
        ),
    ]
