# Generated by Django 4.2.5 on 2023-09-12 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roleruleverb',
            name='Role',
        ),
        migrations.AddField(
            model_name='roleruleverb',
            name='RoleRule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.rolerule'),
        ),
    ]
