# Generated by Django 4.2.5 on 2023-09-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=256)),
                ('ip', models.CharField(max_length=128)),
                ('cpu', models.CharField(max_length=128)),
                ('memory', models.CharField(max_length=128)),
                ('os', models.CharField(max_length=128)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('permission', models.CharField(max_length=128)),
            ],
        ),
    ]
