# Generated by Django 4.2.5 on 2023-09-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hosts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='permission',
            new_name='position',
        ),
    ]
